#!/bin/bash

# Get current date and time in ISO format
CURRENT_DATE=$(date -Iseconds)

# Set the commit date to current date
export GIT_COMMITTER_DATE="$CURRENT_DATE"
export GIT_AUTHOR_DATE="$CURRENT_DATE"

echo "Commit date set to: $CURRENT_DATE"
